name: Build and push

on:
  push:
    tags: [ 'v*.*.*' ]

jobs:
  buildAndPush:
    name: Build and push to NuGet
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.x

      - name: Set package version
        run: |
          tag=${{ github.ref_name }}
          echo "package_version=${tag:1}" >> $GITHUB_ENV
        
      - name: Build package
        run: dotnet pack src/Serilog.Sinks.MementoGroup/Serilog.Sinks.MementoGroup.csproj -c Release -p:PackageVersion=${{ env.package_version }} -o nupkgs
      
      - name: Push to NuGet
        run: dotnet nuget push "nupkgs/Serilog.Sinks.MementoGroup.${{ env.package_version }}.nupkg" --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_WRITE_TOKEN }}
