name: Tests

on:
  workflow_dispatch:
  pull_request:
    types: [ opened, reopened ]
    branches:
      - master

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  runTests:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.x

      - name: Run tests
        run: dotnet test -c Release -l trx --results-directory results --collect "XPlat Code Coverage"
      
      - name: Publish test results
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Tests
          path: results/*.trx
          reporter: dotnet-trx

      - name: Publish code coverage results
        uses: irongut/CodeCoverageSummary@v1.3.0
        if: success() || failure()
        with:
          filename: 'results/*/coverage.cobertura.xml'
          badge: true
          format: markdown
          output: both

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request' && always()
        with:
          recreate: true
          path: code-coverage-results.md
        
      - name: Write to Job Summary
        if: success() || failure()
        run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
